### ISSUE TITLE
gitlab is missing Repository::$namespace

### ISSUE THREAD

**Issue by tolry** [DavidBadura/git-webhooks#8]
I'll try to get some example xml data for easier reproduction, but it seems as if namespace/group is not used on gitlab push events. Or maybe this is a SimpSpector issue concerning old data.

**Comment by DavidBadura** [comment]
we should refresh the fixtures: https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/web_hooks/web_hooks.md

**Comment by tolry** [comment]
:+1: thx
